path:
    img_path : '/content/drive/MyDrive/Masterarbeit/PhenoBenchSubset/'
    out_path : '/content/drive/MyDrive/Masterarbeit/'

hyperparameter:
    numEpochs : 200
    batch_size : 8
    learning_rate : 0.001
    # num_imgs : now taking all

model:
    model_name : 'semantic_segmentation_model_phenobench_'
    num_classes : 3
    encoder : 'efficientnet-b0'

print:
    print_freq : 100
    save_freq : 25