path:
    img_path : '/cache/molave/PhenoBench/'
    out_path : './results/'

hyperparameter:
    # Training Parameters:
    numEpochs : 100
    batch_size : 16
    learning_rate : 0.0001
    img_size : 256
    # Noise Parameters:
    instance_noise_factor : 0
    random_noise_factor : 0
    dilation_first : True
    erosion_iter : 0
    dilation_iter : 0
    kernel_size_di_er : 0
    add_instances_min : 0
    add_instances_max : 0
    add_instances_radius : 0
    cut_instance_factor : 0.5
    cut_factor : 0.5
    # num_imgs : now taking all

model:
    model_name : 'phenobench_'
    num_classes : 3
    encoder : 'efficientnet-b0'
    weights : None
    seed : 4

print:
    print_freq : 50
    save_freq : 25
