path:
    img_path : '/cache/molave/PhenoBench/'
    out_path : './results/'

hyperparameter:
    numEpochs : 100
    batch_size : 16
    learning_rate : 0.0001
    img_size : 256
    instance_noise_factor : 0.2
    random_noise_factor : 0
    erosion_iter : 0
    dilation_iter : 0
    # num_imgs : now taking all

model:
    model_name : 'phenobench_'
    num_classes : 3
    encoder : 'efficientnet-b0'
    weights : None
    seed : 123

print:
    print_freq : 50
    save_freq : 25
